#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I../rGUI -Isrc
CFLAGS = -O3 -std=c++14
RESINC = 
LIBDIR = 
LIB = ../../../../../usr/local/lib/liballegro.so ../../../../../usr/local/lib/liballegro_acodec.so ../../../../../usr/local/lib/liballegro_audio.so ../../../../../usr/local/lib/liballegro_color.so ../../../../../usr/local/lib/liballegro_dialog.so ../../../../../usr/local/lib/liballegro_font.so ../../../../../usr/local/lib/liballegro_image.so ../../../../../usr/local/lib/liballegro_main.so ../../../../../usr/local/lib/liballegro_memfile.so ../../../../../usr/local/lib/liballegro_physfs.so ../../../../../usr/local/lib/liballegro_primitives.so ../../../../../usr/local/lib/liballegro_ttf.so ../../../../../usr/local/lib/liballegro_video.so
LDFLAGS = -s

INC_DEBUG = $(INC) -I../rGUI -Isrc
CFLAGS_DEBUG = $(CFLAGS) -Wall -std=c++14 -pg -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-l../../../../../usr/local/lib/liballegro.so -l../../../../../usr/local/lib/liballegro_acodec.so -l../../../../../usr/local/lib/liballegro_audio.so -l../../../../../usr/local/lib/liballegro_color.so -l../../../../../usr/local/lib/liballegro_dialog.so -l../../../../../usr/local/lib/liballegro_font.so -l../../../../../usr/local/lib/liballegro_image.so -l../../../../../usr/local/lib/liballegro_main.so -l../../../../../usr/local/lib/liballegro_memfile.so -l../../../../../usr/local/lib/liballegro_physfs.so -l../../../../../usr/local/lib/liballegro_primitives.so -l../../../../../usr/local/lib/liballegro_ttf.so -l../../../../../usr/local/lib/liballegro_video.so
LDFLAGS_DEBUG = $(LDFLAGS) -pg
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/librGUI.a

INC_RELEASE = $(INC) -I../rGUI -Isrc
CFLAGS_RELEASE = $(CFLAGS) -O3 -Wall -std=c++14
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-l../../../../../usr/local/lib/liballegro.so -l../../../../../usr/local/lib/liballegro_acodec.so -l../../../../../usr/local/lib/liballegro_audio.so -l../../../../../usr/local/lib/liballegro_color.so -l../../../../../usr/local/lib/liballegro_dialog.so -l../../../../../usr/local/lib/liballegro_font.so -l../../../../../usr/local/lib/liballegro_image.so -l../../../../../usr/local/lib/liballegro_main.so -l../../../../../usr/local/lib/liballegro_memfile.so -l../../../../../usr/local/lib/liballegro_physfs.so -l../../../../../usr/local/lib/liballegro_primitives.so -l../../../../../usr/local/lib/liballegro_ttf.so -l../../../../../usr/local/lib/liballegro_video.so
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/librGUI.a

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/BigBitmap.o $(OBJDIR_DEBUG)/src/BitmapButton.o $(OBJDIR_DEBUG)/src/Button.o $(OBJDIR_DEBUG)/src/CheckBox.o $(OBJDIR_DEBUG)/src/ClickableText.o $(OBJDIR_DEBUG)/src/InputField.o $(OBJDIR_DEBUG)/src/ScrollBar.o $(OBJDIR_DEBUG)/src/ScrollableArea.o $(OBJDIR_DEBUG)/src/SingleKeyInputField.o $(OBJDIR_DEBUG)/src/SlideBar.o $(OBJDIR_DEBUG)/src/widgetbase.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/BigBitmap.o $(OBJDIR_RELEASE)/src/BitmapButton.o $(OBJDIR_RELEASE)/src/Button.o $(OBJDIR_RELEASE)/src/CheckBox.o $(OBJDIR_RELEASE)/src/ClickableText.o $(OBJDIR_RELEASE)/src/InputField.o $(OBJDIR_RELEASE)/src/ScrollBar.o $(OBJDIR_RELEASE)/src/ScrollableArea.o $(OBJDIR_RELEASE)/src/SingleKeyInputField.o $(OBJDIR_RELEASE)/src/SlideBar.o $(OBJDIR_RELEASE)/src/widgetbase.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(AR) rcs $(OUT_DEBUG) $(OBJ_DEBUG)

$(OBJDIR_DEBUG)/src/BigBitmap.o: src/BigBitmap.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BigBitmap.cpp -o $(OBJDIR_DEBUG)/src/BigBitmap.o

$(OBJDIR_DEBUG)/src/BitmapButton.o: src/BitmapButton.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BitmapButton.cpp -o $(OBJDIR_DEBUG)/src/BitmapButton.o

$(OBJDIR_DEBUG)/src/Button.o: src/Button.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Button.cpp -o $(OBJDIR_DEBUG)/src/Button.o

$(OBJDIR_DEBUG)/src/CheckBox.o: src/CheckBox.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CheckBox.cpp -o $(OBJDIR_DEBUG)/src/CheckBox.o

$(OBJDIR_DEBUG)/src/ClickableText.o: src/ClickableText.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ClickableText.cpp -o $(OBJDIR_DEBUG)/src/ClickableText.o

$(OBJDIR_DEBUG)/src/InputField.o: src/InputField.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/InputField.cpp -o $(OBJDIR_DEBUG)/src/InputField.o

$(OBJDIR_DEBUG)/src/ScrollBar.o: src/ScrollBar.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScrollBar.cpp -o $(OBJDIR_DEBUG)/src/ScrollBar.o

$(OBJDIR_DEBUG)/src/ScrollableArea.o: src/ScrollableArea.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ScrollableArea.cpp -o $(OBJDIR_DEBUG)/src/ScrollableArea.o

$(OBJDIR_DEBUG)/src/SingleKeyInputField.o: src/SingleKeyInputField.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SingleKeyInputField.cpp -o $(OBJDIR_DEBUG)/src/SingleKeyInputField.o

$(OBJDIR_DEBUG)/src/SlideBar.o: src/SlideBar.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SlideBar.cpp -o $(OBJDIR_DEBUG)/src/SlideBar.o

$(OBJDIR_DEBUG)/src/widgetbase.o: src/widgetbase.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/widgetbase.cpp -o $(OBJDIR_DEBUG)/src/widgetbase.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/src/BigBitmap.o: src/BigBitmap.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BigBitmap.cpp -o $(OBJDIR_RELEASE)/src/BigBitmap.o

$(OBJDIR_RELEASE)/src/BitmapButton.o: src/BitmapButton.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BitmapButton.cpp -o $(OBJDIR_RELEASE)/src/BitmapButton.o

$(OBJDIR_RELEASE)/src/Button.o: src/Button.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Button.cpp -o $(OBJDIR_RELEASE)/src/Button.o

$(OBJDIR_RELEASE)/src/CheckBox.o: src/CheckBox.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CheckBox.cpp -o $(OBJDIR_RELEASE)/src/CheckBox.o

$(OBJDIR_RELEASE)/src/ClickableText.o: src/ClickableText.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ClickableText.cpp -o $(OBJDIR_RELEASE)/src/ClickableText.o

$(OBJDIR_RELEASE)/src/InputField.o: src/InputField.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/InputField.cpp -o $(OBJDIR_RELEASE)/src/InputField.o

$(OBJDIR_RELEASE)/src/ScrollBar.o: src/ScrollBar.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScrollBar.cpp -o $(OBJDIR_RELEASE)/src/ScrollBar.o

$(OBJDIR_RELEASE)/src/ScrollableArea.o: src/ScrollableArea.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ScrollableArea.cpp -o $(OBJDIR_RELEASE)/src/ScrollableArea.o

$(OBJDIR_RELEASE)/src/SingleKeyInputField.o: src/SingleKeyInputField.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SingleKeyInputField.cpp -o $(OBJDIR_RELEASE)/src/SingleKeyInputField.o

$(OBJDIR_RELEASE)/src/SlideBar.o: src/SlideBar.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SlideBar.cpp -o $(OBJDIR_RELEASE)/src/SlideBar.o

$(OBJDIR_RELEASE)/src/widgetbase.o: src/widgetbase.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/widgetbase.cpp -o $(OBJDIR_RELEASE)/src/widgetbase.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

